##---------------------------------------------------------------------------------------
##Parameters for building a library (needs some rearranging/rework

custom_glycans_list = (False, ['H3N2'])
'''custom_glycans_list (list of boolean and list) allows you to only search for target
   glycans, by setting the first parameter to True and inputing the target glycans in the
   list, as strings of formulas. If True, overrides imp_exp_library.
   Monosaccharides accepted: Hexoses (H), HexNAc (N), Acetyl Sialic Acid (S), Glycolil
   Sialic Acid (G), Deoxyhexose (F).
'''
min_max_monos = (5, 18)
min_max_hex = (3, 10)
min_max_hexnac = (2, 8)
min_max_sia = (0, 4)
min_max_fuc = (0, 2)
min_max_ac = (0, 4)
min_max_gc = (0, 0)
'''"min_max"-leading parameters (tuple with min and max amount) are used to specify the
   monosaccharides amounts.
'''
force_nglycan = True
'''force_nglycan (boolean) is used to force some monosaccharides compositions associated
   with N-Glycans biologically known features.
'''
max_adducts = {'H' : 3, 'Na' : 1}
'''max_adducts (dictionary containing the compositions of each atomic adduct and the
   maximum amounts of it) indicates the desired adducts and their maximum amount.
'''
max_charges = 3
'''max_charges (int) limits the maximum amount of calculated charges for each glycan.
'''
intensoids_clumping = 0.05
'''intensoids_clumping (float) is the tolerance to clump together isotopologic peaks
   naturally close-together. Not tested for very small values. Recommended to set at a
   value of at least 5 times tolerance used on analysis. Smaller values might be useful
   for acquisitions done on very high accuracy equipments, such as FT-ICR.
'''
tag_mass = 219.173
'''tag_mass (float) if a reducing end tag is added to the glycans, insert its added mass
   here. If not reducing end tag is added to the glycans, set this value to 0.
'''
fast_iso = True
'''fast_iso (boolean) allows you to calculate the isotopic distribution of glycans based
   only on carbon isotopes (fast, innacurate) or on all the atoms isotopes (VERY SLOW,
   very accurate). If set to False, library building may take many hours.
'''
imp_exp_library = (True, False)
'''imp_exp_library (tuple of booleans) can be used to import a glycans library previously
   generated by this script (when first boolean = True) or to export the library you
   generate to use in future analysis without having to build a new library (when second
   boolean = True).
   !!! Default exported/imported library file name = glycans_library.py
'''
only_gen_lib = False
'''only_gen_lib (boolean) determines if the script should stop after generating library
   or proceed with data analysis.
'''
